from typing import Protocol, runtime_checkable


@runtime_checkable
class IPDataWriter(Protocol):
    def add_or_update_ip(self, ip: str, channel: str, data: dict) -> bool: ...
    def delete_ip(self, ip: str) -> bool: ...
    def delete_channel(self, ip: str, channel: str) -> bool: ...


@runtime_checkable
class IPDataReader(Protocol):
    def get_ip_data(self, ip: str) -> dict | None: ...
    def get_channel_data(self, ip: str, channel: str) -> dict | None: ...
    def list_all_ips(self) -> list[str]: ...
    def list_ip_channels(self, ip: str) -> list[str]: ...
    def search_ips_by_channel(self, channel: str, key: str = None, value: str = None) -> list[str]: ...
    def get_ips_data(self, ips: list[str]) -> dict[str, dict]: ...
    def list_all_ips_data(self, exclude_ips: list[str] | None = None) -> dict[str, dict]: ...


@runtime_checkable
class DomainCache(Protocol):
    def get(self, domain: str) -> dict | None: ...
    def set(self, domain: str, data: dict) -> None: ...
